# Generated by Django 4.2.4 on 2023-09-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students10TH2019',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=10)),
                ('studentName', models.CharField(max_length=30)),
                ('studentCity', models.CharField(max_length=30)),
                ('studentState', models.CharField(max_length=30)),
            ],
        ),
    ]
