# Generated by Django 4.2.4 on 2023-09-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0004_studentgrades_delete_studentgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=10)),
                ('studentName', models.CharField(max_length=30)),
                ('studentAge', models.IntegerField()),
                ('studentCity', models.CharField(max_length=30)),
                ('studentState', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Students10TH2019',
        ),
    ]
