# Generated by Django 4.2.4 on 2023-09-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentNo', models.IntegerField()),
                ('studentName', models.CharField(max_length=50)),
                ('studentClass', models.IntegerField()),
                ('studentAddress', models.CharField(max_length=100)),
            ],
        ),
    ]
